### ISSUE TITLE
Allow to customize track preparation

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#1066]
### Proposal

Rally defines a standard workflow how tracks are prepared before the actual benchmark is executed. It downloads data and can extract them but more customization is not possible yet desirable. For example, we might want to use the downloaded data only as a template and generate a much larger corpus before the benchmark starts.

_In the following description we will refer to the component that can hook into track preparation as a "track processor". This name may change in the implementation phase._

The solution should have the following capabilities:

* Well defined phases where we can hook into (e.g. during corpus download, after corpus download, etc.)
* Allow modifying metadata on the track (e.g. filesize or doc count of corpus). These need to be available to other components like parameter sources later on.
* Users should be able to pass parameters to the track processor. Note that we already have a validation implemented on Jinja level to ensure that all key-value pairs passed via `--track-params` are already consumed by Jinja and it is not possible to leave parameters "unbound" when a track is loaded. 
* We should expose a high-level API to help with file handling (e.g. provide the current data directory, utilities to read files, etc.) to avoid that track processors need to reimplement low-level file handling code that would already be available in Rally anyway (see e.g. `esrally.utils.io`).
* Ability to skip phases, e.g. if a track processor has already pre-generated files there is no point in generating them again.

Implementation note: We might be able to reimplement some internal components that handle track loading already as track processors (for example, the code handling test mode or task filters) which could be a good validation of the chosen approach.

### Sub tasks

* [x] Define a component interface for a track processor and expand the existing component registry to register also track processors. 
* [x] Change track plugin loader invocations so track processors can be detected and invoked when a track is loaded.
* [x] (Optional) Convert test-mode post-processing to a track processor and register it by default.
* [x] (Optional) Convert task filters to a track processor and register it by default.
* [x] Add the ability to pass parameters to a track processor, preferably via `--track-params`. Note that this may require that we adapt the track file format.
* [x] Provide a standard mechanism for track processors to detect whether they should skip a phase. Maybe track processors can decide this on their own by inspecting output files, maybe we need a (simple) persistence mechanism like a JSON file in a well-defined location and a thin API so track processors can store meta-data.

Moved to a later phase:

* ~Define and expose a high-level file handling API available to track processors.~
