### ISSUE TITLE
Use milliseconds instead of microseconds for relative time

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#1198]
When using an Elasticsearch metrics store, metrics stored in `rally-metrics` contain a `relative-time` key in every record (as this starts from `0` it's useful for comparisons).
The unit of this metric is μs (microseconds) and as such unnecessarily granular and trappy in visualizations and data analysis.

We should change this to `ms` (milliseconds).

As per #1221 the schedule is:

- [x] Rally 2.1.0: `relative-time` is deprecated and Rally adds a new field `relative-time-ms` which contains the relative time in milliseconds. Done in #1221.
- [x] Rally 2.2.0: `relative-time` will be dropped. Rally only populates the field `relative-time-ms` which contains the relative time in milliseconds. Done in #1231.
- [x] Rally 2.2.1: `relative-time` will be reintroduced and contain the relative time in milliseconds. The field `relative-time-ms` will be deprecated. Done in https://github.com/elastic/rally/pull/1273.
- [x] Rally 2.3.0: `relative-time-ms` will be dropped. Done in https://github.com/elastic/rally/pull/1291.
