### ISSUE TITLE
Tasks after Elasticsearch 8.0 release

### ISSUE THREAD

**Issue by pquentin** [elastic/rally#1442]
Now that Elasticsearch 8.0 is out, here's what we want to do in Rally:

- [ ] https://github.com/elastic/rally/pull/1435
- [ ] Test 8.0 instead of 7.6 in integration tests: https://github.com/elastic/rally/blob/master/it/__init__.py#L32
- [ ] Drop `test_prepare_distribution_lt_63_with_plugins` and the related logic
- [ ] On 8.0+ support only names for repository plugins that became modules
- [ ] Upgrade the Python client to 8.0
