### ISSUE TITLE
Add wait-for-completion support to force-merge

### ISSUE THREAD

**Issue by inqueue** [elastic/rally#1726]
Support for the `?wait_for_completion` request parameter should be added to force-merge for configuring its blocking behavior. Force merge operations can take a very long time, resulting in unpredictable behavior when, for example, there is a proxy between the client and Elasticsearch.

The force-merge operation supports a polling mode that repeatedly monitors the tasks API for forcemerge activity once the force merge request times out. It would be best to rely on "wait on completion" instead of the timeout, or at least have it as an option.
```[tasklist]
### Tasks
- [ ] Document that polling mode does not work if there's a proxy between Rally and Elasticsearch
- [ ] Fix polling mode to correctly time out after one second as documented
- [x] Support the `wait_on_completion` parameter
```
