### ISSUE TITLE
More flexible configuration of benchmark candidates

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#195]
Currently, configuration of benchmark candidates is pretty limited: We have only a few combinations available, everything is geared towards single node benchmarks and also all that is hardcoded in the Rally code base. However, we rather want to make the configuration more flexible and also allow want to provision clusters where individual nodes have different roles (dedicated master nodes, data nodes etc.).

Given that #184 is around the corner to provision single nodes and we will implement multi-node provisioning in #71, it is about time that we think about how we can support flexible cluster topologies.

We will take a phased approach:

1. [x] First, we externalize car configuration (#196)
2. [x] next, we will enable benchmarking with plugins (see #60)
3. [x] finally, we add support for multi-node clusters (#71)

### Candidate Management

Similarly to track management via git, we will also use a git repository to manage benchmark candidates. The idea is that users create their own repos but we will provide an official one so users can get started.

The structure in the repo `rally-teams` (team being an analogy for a cluster (consisting of multiple cars)) is as follows:

```
├── cars
│   └── defaults
│       └── config
│           ├── elasticsearch.yml
│           ├── jvm.options
│           └── log4j2.properties
├── plugins
│   └── x-pack
│       ├── config
│       │   └── elasticsearch.yml
│       └── install.cmd
└── teams
    ├── single
    │   └── node.yml
    └── two
        └── node.yml
```

The directories' purpose is:

* `cars`: contains the configuration of a single node (one per sub-directory). The node in the example is called `defaults` and contains just the default (out-of-the-box) configuration of Elasticsearch.
* `plugins`: contains the configuration of plugins (one per sub-directory). The `install.cmd` contains one or more shell commands to install and configure the plugin. The contents of `config/elasticsearch.yml` (if present) will be appended to the already existing `elasticsearch.yml` of the node.
* `teams`: contains the configuration of a cluster (one per sub-directory). The `node.yml` file can override property placeholders either in `track.json` or the car configuration (this is needed to allow e.g. cluster specific settings such as replica count.).

The candidate repositories will be stored in `~/.rally/benchmarks/teams/$REPO_NAME` with the default repo being our official one. `~/.rally/rally.ini` will contain a reference to the available team repos (all that is nothing new and very similar to how tracks are managed today).

### Command line usage

Here are few examples of the envisioned command line usage (examples assume we are on a machine with IP `192.168.1.2`).

```
# This command shows all implicit default values, i.e. this is the same as just invoking: esrally
esrally --team-repository=default --car=defaults --team=single --topology="node:127.0.0.1" --es-plugins=""

# remote deploy a node with car "defaults":
esrally --topology="node:192.168.1.5"

# but this could also get as complex as the following example.
# "master" is a node specification in the team folder (i.e. master.yml instead of the default "node.yml" and we choose a "4gheap" car for it (similarly for "data" and "24gheap")
esrally --team=complex --topology="master:4gheap:192.168.1.5,master:4gheap:192.168.1.6,data:24gheap:192.168.1.7,data:24gheap:192.168.1.8,data:24gheap:192.168.1.9"

# run with X-Pack
# TODO: can we make this work with source builds too?
esrally --es-plugins="x-pack"
```

**Comment by danielmitterdorfer** [comment]
For a later phase we could also think about a "mixin" concept. For example, if we want to run Elasticsearch with the following configuration:

* 4gb heap size (name in example below: `4gheap`)
* assertions enabled (name in example below: `ea`)
* more verbose logging  (name in example below: `verbose`)

We could create "mixin" definitions for all components and then define a car with `--car="4gheap,ea,verbose"`. This could reduce the number of necessary definitions significantly.

**Comment by danielmitterdorfer** [comment]
All sub-tasks are done, thus closing.
