### ISSUE TITLE
Make the track authors' life easier

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#212]
_This is a meta-ticket to collect problems we find when creating tracks and to gather some ideas to make the track authors' life easier._

Here are some problems we are already aware of:

- [ ] Docs are a bit light w.r.t to structuring custom runners (what is the root package when you want to use multiple files and need to import stuff, etc.?)
- [ ] No support for unit-testing custom runners
- [X] No support for benchmarking custom runners or gathering timing info (-> potential client-side bottlenecks). Ideally we'd have some sort of profiling support for that (resolved by #216)
- [x] The git workflow gets overly complex when contributing to Rally's default tracks via pull requests. (solved by `--track-path` so there is no need for git anymore)
- [ ] We could provide a tool to create track data files from existing indices (see e.g. https://gist.github.com/HonzaKral/0fb3f76da529ee380d08).

**Comment by danielmitterdorfer** [comment]
Closing as too unspecific. I also created #444 in favour of the last item.
