### ISSUE TITLE
Prepare Rally for Java 9

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#259]
Java 9 is scheduled for release later this year (see [schedule](http://openjdk.java.net/projects/jdk9/)). A few command line flags and other options have changed and we should prepare Rally to be able to adapt. 

* [x] Change configuration routine to auto-detect the highest (stable) Java version (currently checks only for Java 8 and also asks the user about Java 8 explicitly): Rally has the necessary code in place but we will not release it before Java 9 GA as there are additional restrictions in Elasticearch (e.g. ES master has a bootstrap check to avoid that users start with an early access version of Java 9). In short there is too much potential that users shoot themselves into the foot. If somebody still wants to run on JDK 9 before GA, there is still the possibility to edit Rally's configuration file manually. (see #265)
* [x] Check if it is possible to build Elasticsearch with Java 9: At the moment building Elasticsearch against JDK 9 is possible but a bit involved (Gradle needs to run on JDK 8) and I do not plan to support this scenario.
* [x] Verify that it is possible to run benchmarks with Elasticsearch on Java 9: Positively verified with `esrally --distribution-version=5.3.0`
* [x] Make the `gc` telemetry device work with Java 9 (JVM flags have changed and this fails currently). See #266
* [x] Verify that the `jit` telemetry device works with Java 9.
* [x] Make the `jfr` telemetry device work with Java 9. See #324

**Comment by danielmitterdorfer** [comment]
We will not (test) and support Elasticsearch 1.x on Java 9 as initial testing has shown that it fails out of the box with `java.lang.UnsupportedOperationException: Boot class path mechanism is not supported`. It may be possible to make it work (I did not check) but we will not put any effort into fixing Rally for a version of Elasticsearch that went EOL almost a year ago. 

Note that it is still possible to run Rally with Elasticsearch 1.x and Java 8. You just need to manually set `java.home` in `~/.rally/rally.ini` to a valid JDK 8 installation (`java.home` will replace the current property `java8.home` once #265 is merged).

**Comment by danielmitterdorfer** [comment]
Closing as all subtasks are now resolved.
