### ISSUE TITLE
Open source Rally

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#32]
Before we open source Rally, we have to tackle a few things:

- [x] Check if docs are helpful enough and possibly provide more docs
- [x] Check if error and feedback messages are helpful
- [x] Check if config defaults should be changed to account for non-core devs
- [x] Add README.rst for PyPI
- [x] Upload to PyPI
- [x] Upload user documentation to [readthedocs](https://read-the-docs.readthedocs.org/en/latest/getting_started.html)
- [x] ~~Add some kind of periodic update check as Rally will probably be updated quite often and we want users to upgrade early (e.g. [update_checker](https://github.com/bboe/update_checker))~~ (we don't want to bug users and leave it for now)
- [x] Check if everything regarding licensing is correctly done (also: License files for benchmarks!)
- [x] ~~Optional: Generate Pydocs~~ (we ignore this for now as Rally is currently more meant to be used as a tool instead of a library and thus the API docs play just a role for developers working on Rally itself)
- [x] Announce on [Discuss](https://discuss.elastic.co/c/annoucements) (anywhere else?)
- [x] Write a blog post about Rally
- [x] Document contribution guidelines
- [x] Set up CLA check (ask Karel)

**Comment by danielmitterdorfer** [comment]
Released version 0.2.0 as of today:

* https://pypi.python.org/pypi/esrally/0.2.0
* https://discuss.elastic.co/t/rally-0-2-0-released/47784
* https://www.elastic.co/blog/announcing-rally-benchmarking-for-elasticsearch
