### ISSUE TITLE
Allow to use Rally without knowing about challenges

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#474]
_Note: This is a follow-up from #455._

### Purpose

In order to make it simpler for new users, "challenges" will become optional in Rally. We will however not get rid of them because it makes sense to keep them to provide structure for more complex tracks.

### Tasks

* [x] Simplify the track format so if there is only one challenge, users can specify the `schedule` element on top-level.
* [x] Hide the notion of a challenge from UI output in these simple cases.
* [x] State more clearly in the docs that challenges are a more advanced concept and that it is not necessary to use them when getting started.
