### ISSUE TITLE
Improve flexibility of benchmarks

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#53]
## Vision (Short Term)

After we have implemented everything concerning this meta-ticket, users will be able to define their own tracks separately from Rally. Tracks will then be able to move at a different pace than Rally. Also users can have their own private tracks if they want to and tracks can be also run on different versions of Elasticsearch (but concerning just the track-specific stuff, we do not cover version-aware cluster provisioning here (i.e. if the startup options format changes you're still screwed)).

Maintenance of tracks across multiple versions of Elasticsearch may involve a bit of manual work but if needed we could add tool support (I'd just not consider it a priority at the moment, we have larger issues to tackle (but happy to receive PRs)). So we solve the maintenance part primarily by documenting on how to do it.

These are the relevant sub-tickets:

* [X] #61: Allow more flexibility over what exact steps are executed overall in Rally
* [X] #52: Allow more control over how the benchmark candidate is configured
* [x] #26: Separate track specification from track execution
* [x] #69 Support tracks across multiple versions of Elasticsearch
* [x] #99 Support multiple track repositories
