### ISSUE TITLE
Externalize log rotation

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#539]
In #503 we implemented that Rally's logging can be configured via a file. Our default configuration contains the following handler definition:

```json
    "rally_log_handler": {
      "class": "logging.handlers.TimedRotatingFileHandler",
      "filename": "${LOG_PATH}/rally.log",
      "utc": true,
      "when": "midnight",
      "backupCount": 14,
      "encoding": "UTF-8",
      "formatter": "normal",
      "filters": ["isActorLog"]
    }
```

This is problematic because Rally uses multiple processes and there is a lurking race condition when rolling log files (which we had already found in #263). Hence, we will stop rotating logs from within Rally and leverage established tools like `logrotate` for that.

### Tasks

* [x] Change the current log configuration template to use [`WatchedFileHandler`](https://docs.python.org/3/library/logging.handlers.html#watchedfilehandler) which is meant to be used with tools like `logrotate`
* [x] Determine a suitable `logrotate` configuration for Rally and provide a snippet in our docs.
* [x] Implement a check on Rally startup that ensures that the new configuration file template is used  (backup the old one if present and replace it with the new one)

Note: `WatchedFileHandler` uses the `stat` system call to check whether the inode of the log file has changed to determine whether to reopen the file. The file system metadata are cached. Also, this check is done every time a log line is written. In steady state this happens only a couple of times per minute in the default logging configuration. Therefore, we consider the performance impact of using `WatchedFileHandler` by default negligible.
