### ISSUE TITLE
Allow benchmarking with plugins

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#60]
Currently we can only provision and benchmark a vanilla Elasticsearch instance but we should be able to benchmark also with specific plugins enabled to determine their performance impact.

For the initial implementation we will not support plugins built from sources and require that they are installed from a plugin repository.

#### Tasks

* [x] Enhance the team repository so it contains information about plugins
* [x] Have the provisioner use this information to install and configure plugins
* [x] Define and implement the concept of "install hooks" to run arbitrary Python code at defined points in time when installing a plugin (e.g. to configure certificates for x-pack security)
* [x] Allow to use multiple config bases to avoid bloat and duplication in configs (this allows to run e.g. `--elasticsearch-plugins="x-pack:security+graph"`).
* [x] Allow to specify explicit download URLs for plugins (e.g. for snapshots). These should be overridable in `rally.ini` or on the command line
* [x] Add plugin-metadata to metrics records. Rally will detect installed plugins via the cluster stats API. This allows us to be agnostic of how the plugins got installed (Rally could also be invoked with the pipeline `benchmark-only`). We will lose some information (e.g. the plugin config that has been used) but if this is important to the user, they can use [tags](http://esrally.readthedocs.io/en/latest/command_line_reference.html#user-tag) for that.
