### ISSUE TITLE
Migrate all integration tests to new infrastructure

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#975]
In https://github.com/elastic/rally/pull/919 we added a new integration test infrastructure based on `py.test` to replace the existing shell script `integration-test.sh`. While some of the integration tests have already been migrated, a couple of them are still left:

* [x] `test_proxy_connection` https://github.com/elastic/rally/pull/1029
* [x] `test_configure` #1023
* [x] `test_distribution_fails_with_wrong_track_params`: https://github.com/elastic/rally/pull/977
* [x] `test_docker_dev_image` #1026 
* [x] Remove `integration-test.sh` and its invocation in `tox.ini` https://github.com/elastic/rally/pull/1029

**Comment by bartier** [comment]
@danielmitterdorfer Can I try to migrate the test_docker_dev_image tests? I did some tests with the [first one](https://github.com/bartier/rally/blob/test-docker-dev-image/it/docker_dev_image_test.py) and it apparently worked as it should.

**Comment by danielmitterdorfer** [comment]
@bartier sure, thanks for helping out. I think it would be good to get a preliminary review on the migration of the first test and then expand to further tests (in the same PR).
