### ISSUE TITLE
Add reference docs for the load generator

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#981]
We should add reference docs that describe relevant information about the load generator from a user perspective (this needs to be a new page in the docs). Two aspects are:

* [ ] Provide a high-level introduction and specifically document how clients are assigned to OS processes and load generator hosts - will be addressed by @hub-cap 
* [ ] Measure and document how throughput / number of active clients as a function of the number of clients specified - will be addressed by @ebadyano 

While we're at it, we should also:

* [ ] move the [scheduler docs from the track reference](https://esrally.readthedocs.io/en/stable/track.html#choosing-a-schedule) to the new page - will be addressed by @hub-cap

**Comment by dliappis** [comment]
@hub-cap / @ebadyano I've edited this issue:

1. I've added a task (owned by me) to provide charts describing the interplay between `bulk_size`, `num of clients` and `target-throughput`/`target-interval`.

2. I moved the item to change the location of the scheduler docs to be after 1. The charts from 1. should be placed there. @hub-cap owns this.

@hub-cap Here are the charts I came up with (I can provide them in other formats too like svg, pdf, without background etc.):

## Target-throughput with 2 clients

![Rally schedule examples - target-throughput_2,clients_2](https://user-images.githubusercontent.com/1754575/86762974-af0c7500-c04f-11ea-8e54-8319c7e7fe64.png)

## Target-interval with 1 client

![Rally schedule examples - target-interval_2,clients_1](https://user-images.githubusercontent.com/1754575/86765274-9dc46800-c051-11ea-8032-613f2988e765.png)

## Target-interval with 2 clients

![Rally schedule examples - target-interval_2,clients_2](https://user-images.githubusercontent.com/1754575/86765089-5dfd8080-c051-11ea-94b4-8d606cecb0fc.png)
